### PR TITLE
New

### PR DESCRIPTION
**Pull request by lillian-busingye**
Added a title for the document

### CODE REVIEW

**Comment by lillian-busingye** [comment]
@Ann-Barnshaw WDYT of the product now?

**Comment by Ann-Barnshaw** [comment]
Hi @lillian-busingye ,

I have git pulled your work, however, when I go live, I don't see any changes made.

**Comment by lillian-busingye** [comment]
@Ann-Barnshaw kindly check out the new changes.

**Comment by Ann-Barnshaw** [comment]
@lillian-busingye , looks great! 

Nice job.

**Pull request merged**
